import type { Analysis } from "./api";

export function analysisToMarkdown(a: Analysis): string {
  const fm = [
    "---",
    `title: "${a.title.replace(/"/g, '\\"')}"`,
    `genre: ${a.genre}`,
    `score: ${a.engagementScore}`,
    `date: ${new Date(a.createdAt).toISOString()}`,
    "---",
    "",
  ].join("\n");

  const factorTable = [
    "| Factor | Score | Weight | Note |",
    "|---|---:|---:|---|",
    ...a.factors.map((f) => `| ${f.name} | ${f.score.toFixed(1)} | ${(f.weight * 100).toFixed(0)}% | ${f.note} |`),
  ].join("\n");

  const suggestions = ["high", "medium", "low"]
    .map((impact) => {
      const items = a.suggestions.filter((s) => s.impact === impact);
      if (!items.length) return "";
      return `### ${impact[0].toUpperCase()}${impact.slice(1)} impact\n\n${items
        .map((s) => `- **${s.title}** _(${s.area})_ — ${s.detail}`)
        .join("\n")}`;
    })
    .filter(Boolean)
    .join("\n\n");

  const cliff = a.cliffhangers
    .map((c) => `- **Beat ${c.beat} · ${c.scene}** — _${c.effectiveness}_ — ${c.rationale}`)
    .join("\n");

  return `${fm}
# ${a.title}

> ${a.summary}

**Genre:** ${a.genre}  ·  **Engagement:** ${a.engagementScore} / 10  ·  **Confidence:** ${(a.confidence * 100).toFixed(0)}%

## Strengths
${a.strengths.map((s) => `- ${s}`).join("\n")}

## Weaknesses
${a.weaknesses.map((s) => `- ${s}`).join("\n")}

## Engagement factors
${factorTable}

## Suggestions
${suggestions}

## Cliffhangers
${cliff}

---
_Generated by ScriptIQ — editorial coverage_
`;
}

export function downloadMarkdown(a: Analysis) {
  const md = analysisToMarkdown(a);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${a.title.replace(/[^\w\-]+/g, "_").toLowerCase()}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function openPrintReport(id: string) {
  window.open(`/results/${id}/print`, "_blank", "noopener,noreferrer");
}
